# Nützliches für Machine Leaning in Python I


## Numpy Arrays

In [1]:
#wie in C
arr =  [1,2,3,4]
arr

[1, 2, 3, 4]

In [2]:
arr[1] = 100
print(arr)
print(arr[1])

[1, 100, 3, 4]
100


In [3]:

import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8])
print(numbers)
numbers?


[1 2 3 4 5 6 7 8]


Type:        ndarray
String form: [1 2 3 4 5 6 7 8]
Length:      8
File:        c:\users\yhutter\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype :

In [4]:
#Spezielle Arrays mit numpy
import numpy as np
numbers = np.array([1,2,3,4,5,6,7,8])
#numbers?

print(numbers)
print(numbers * 2)
print(numbers - 2)
print(numbers < 4)
# in anderen Programmiersprachen ist das viel komplizierter und in 
# Python ist das auch speziell optimiert.

[1 2 3 4 5 6 7 8]
[ 2  4  6  8 10 12 14 16]
[-1  0  1  2  3  4  5  6]
[ True  True  True False False False False False]


In [ ]:
#Filtern von numpy-Arrays mit [ ... ]   
print('Einzelne Listenelemente ausgeben')
print( numbers[0] ) # Zugriff auf einzelnes Element
print( numbers[[0]]) # Zugriff auf einzelnes Element, aber dieses wird als Liste verpackt
print( numbers[[0,3,4]]) # Liste als Zugriffsargument: Aufzählung
print( numbers[[-1]]) # gib das letzte Element aus... hier als Liste
print( numbers[-3]) # gib das Drittletzte aus... hier nur der Wert selber
print('Erstreckungsbereiche von Listenelemente wie bei Excel ausgeben')
print( numbers[0:5]) # Liste von... bis ... a la Excel
print( numbers[:5]) # ... man kann die 0 auch weglassen
print( numbers[5:8]) # Liste von... bis ... a la Excel
print( numbers[5:]) # ... man kann die 0 auch weglassen
print( numbers[:]) # ... nur ':' gibt dann eben alles aus
print('Listenelemente mit Intervallücken zugreifen')
print( numbers[::2]) # ein zweiter Doppelpunkt ermöglicht ein Intervall-Argument - also bei 2 nur jede zweite Zahl
print( numbers[::-2]) # das Intervall-Argument kann auch negativ sein. Es fängt dann aber von hinten an!
print( numbers[::-1]) # Intervall-Argument -1 dreht die Liste um

#das Argument kann man auch als Variable speichern

In [ ]:
np.ones(10)

In [ ]:
np.zeros(10)

In [ ]:
np.zeros(10) + 2

In [ ]:
np.repeat(101,50)

In [ ]:
np.arange(1,1000)

In [ ]:
sum(np.arange(1,100))

In [5]:
np.linspace(0,13,10)

array([ 0.        ,  1.44444444,  2.88888889,  4.33333333,  5.77777778,
        7.22222222,  8.66666667, 10.11111111, 11.55555556, 13.        ])

## Matritzen

In [ ]:
# Die Matrix: in Python ein zweidimensionales Array (kein Kinofilm)

matrix = [ [11, 12, 13, 14],
           [21, 22, 23, 24],
           [31, 32, 33, 34],
           [41, 42, 43, 44]
         ]
            

In [ ]:
matrix

In [ ]:
# Accessing....
zweiteZelleErsteZeile = matrix[0][1]
zweiteZelleErsteZeile

In [ ]:
# Dicing....
ersteZeile = matrix[0]
ersteZeile

In [ ]:
# in Numpy-Matrix verwandeln
numpyMatrix = np.array(matrix)

In [ ]:
# Nur mit Numpy geht auch Slicing....

# ":" steht ür alle Zeilen!
ersteSpalte = numpyMatrix[:,[0]]
ersteSpalte

In [ ]:
ersteUndVierteSpalte = numpyMatrix[:,[0,3]]
ersteUndVierteSpalte

In [ ]:
# Prinzip:  <von>:<nach>:<step>
ausDerMitte = numpyMatrix[1:3,1:3]
ausDerMitte

In [ ]:
print(numpyMatrix)
np.rot90(numpyMatrix)
# Linksrotation der Matrix um 90°

In [ ]:
#Metainformation über eine Numpy-Matrix ermitteln:
numpyMatrix.shape

In [6]:
# Matrix aus Array erzeugen
a = np.arange(1,7)
print("aus: ")
print(a)
print("wird: ")
b = a.reshape(2,3)
print(b)
print("und wieder zurück ")
c = b.reshape(6)
print(c)

aus: 
[1 2 3 4 5 6]
wird: 
[[1 2 3]
 [4 5 6]]
und wieder zurück 
[1 2 3 4 5 6]


In [ ]:
#Reshape kann auch selbst bestimmen, wie umgebrochen werden soll:
np.arange(1,7).reshape(2,-1)

In [ ]:
#oder:
np.arange(1,7).reshape(-1,2)

In [ ]:
#und wenn man nur flachklopfen will, 
#ohne zu wissen wieviele Elemente drin sind:
c.reshape(-1)

## Von der Datenstruktur zum Dataframe

In [ ]:
# Hastableartige Strukturen
dataStructure = {
  "calories": [380, 390, 420],
  "duration": [40, 45, 50 ]
}


In [ ]:
dataStructure["calories"]

In [ ]:
dataStructure

## Plotten

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.scatter(dataStructure["calories"], dataStructure["duration"])
#plt.show()

In [ ]:
import pandas as pd 
dataFrame = pd.DataFrame(dataStructure)

In [ ]:
dataFrame

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.scatter(dataFrame["calories"], dataFrame["duration"])

In [ ]:
dataFrame["calories"]

In [ ]:
dataFrame[["calories"]]

In [ ]:
dataFrame[["duration"]]

In [ ]:
dataFrame["calories"]

In [ ]:
#Plotten von Werten
plt.plot(dataFrame["calories"], dataFrame["duration"], color = "red")

#und Punkte dazu:
plt.scatter(dataFrame["calories"], dataFrame["duration"], color = "blue" )





In [ ]:
plt.scatter(dataFrame["calories"], dataFrame["duration"], color = "blue" )


In [ ]:
x = np.arange(-200,200,50)
plt.plot(x,x**2)

In [ ]:
np.arange(0,20,1)**2

In [ ]:
dataFrame

In [ ]:
dataFrame["neueSpalte"] = np.arange(1,4)

In [ ]:
dataFrame
